### ISSUE TITLE
soup puzzle bug

### ISSUE THREAD

**Issue by fulfwlply** [kbalisnomo/soup-game#6]
found on branch kyle-soup. OS: windows
bug when deselecting letters in top spaces. once deselected, the letters return to their original positions, overlapping any letter that transports into that space.
once selecting the space with 2 letters, both letters occupy empty spaces.

**Comment by kbalisnomo** [comment]
Fixed bug when deselecting letters in top spaces letters would return to their original positions. Now the letters go to their new position and no longer overlap.
